package services;

import java.util.Collection;
import java.util.Date;

import javax.transaction.Transactional;

import org.joda.time.DateTime;
import org.joda.time.Days;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.util.Assert;

import repositories.BillRepository;
import domain.Banner;
import domain.Bill;
import domain.Message;
import domain.Sponsor;

@Service
@Transactional
public class BillService {

	// managed repository---------------------
	@Autowired
	private BillRepository billRepository;

	// supporting services -------------------
	@Autowired
	private SponsorService sponsorService;

	@Autowired
	private AdministratorService administratorService;

	@Autowired
	private BannerService bannerService;

	@Autowired
	private MessageService messageService;

	// Basic CRUD methods --------------------
	public Bill create(Sponsor sponsor) {
		sponsor = sponsorService.findByPrincipal();
		Assert.notNull(sponsor, "Dear user, you are not a sponsor.");
		Bill created;
		created = new Bill();
		Date moment = new Date(System.currentTimeMillis() - 100);
		created.setCreationDate(moment);
		created.setSponsor(sponsor);
		return created;
	}

	public Bill findOne(int billId) {
		Bill retrieved;
		retrieved = billRepository.findOne(billId);
		return retrieved;
	}

	public Collection<Bill> findAll() {
		Collection<Bill> bills;
		bills = billRepository.findAll();
		return bills;
	}

	public Bill save(Bill bill) {
		Sponsor sponsor = sponsorService.findByPrincipal();
		Assert.notNull(sponsor, "Dear user, you are not a sponsor.");
		Bill saved;
		saved = billRepository.save(bill);
		return saved;
	}

	public void delete(Bill bill) {
		billRepository.delete(bill);
	}

	// Auxiliary methods ---------------------

	// Our other bussiness methods -----------
	public Double[][][] calculateAvgDevPaidAndUnpaidBills() {
		return billRepository.calculateAvgDevPaidAndUnpaidBills();
	}

	public Bill payBill(Bill bill) { // Requirement 33.3
		Sponsor sponsor = sponsorService.findByPrincipal();
		Assert.notNull(sponsor, "Dear user, you are not a sponsor.");
		Date moment = new Date(System.currentTimeMillis() - 100);
		bill.setPaymentDate(moment);
		Bill saved = this.save(bill);
		return saved;
	}

	public void computeProcedureMonthlyBills() { // Requirement 34.2
		administratorService.checkAdministrator();
		Date moment = new Date(System.currentTimeMillis() - 1);
		Double cost;
		Collection<Banner> banners;
		for (Sponsor s : sponsorService.findAll()) {
			cost = billRepository.computeBillCost(s.getId());
			Bill bill = create(s);
			String description = "";
			bill.setCost(cost);
			bill.setCreationDate(moment);
			banners = bannerService.paidBanners(s.getId());
			for (Banner b : banners) {
				description += b.getURL() + " ";
				b.setTimesShownMonth(0);
				bannerService.save(b);
			}
			bill.setDescription(description);
			bill.setSponsor(s);
			billRepository.save(bill);
		}
	}

	public void sendMessageSponsors() { // Requirement 34.3
		administratorService.checkAdministrator();
		Message message;
		Collection<Bill> bills;
		Date moment = new Date(System.currentTimeMillis() - 1);
		bills = billRepository.generateBills();
		for (Bill b : bills) {
			if (b.getPaymentDate() == null) {
				int days = Days.daysBetween(new DateTime(b.getCreationDate()),
						new DateTime(moment)).getDays();
				if (days > 30) {
					message = messageService.create(b.getSponsor());
					message.setTitle(b.getDescription() + " has not been paid.");
					message.setBody("This is an autogenerated message to notify you that you have not paid these bills.");
					messageService.send(message);
				}
			}
		}
	}
	
	public Collection<Bill> findAllByPrincipal(){ // Browse his monthly bills
		Sponsor sponsor = sponsorService.findByPrincipal();
		Assert.notNull(sponsor, "Dear user, you are not a sponsor.");
		Collection<Bill> bills;
		sponsor = sponsorService.findByPrincipal();
		bills = billRepository.findBillBySponsor(sponsor.getId());
		return bills;
	}
}
